#!/usr/bin/env node
var pictureSorter = require("./index.js");
var fs = require("fs");
var argv = require("minimist")(process.argv);
var src = argv['s'] !== undefined;
var dst = argv['d'] !== undefined;

if (!(src && dst)) {
  console.log("");
  console.log("Usage: picture-sorter options");
  console.log("");
  console.log("   Ex: picture-sorter -m --use-modif-date -s ~/tmp -d ~/tmp/sorted");
  console.log("");
  console.log("Options:");
  console.log("");
  console.log("  -m - Move files from source.");
  console.log("  -s - Source folder.");
  console.log("  -d - Destionation folder.");
  console.log("  -v - Verbose mode.");
  console.log("  --use-modif-date - If no exif info is found, use file modification date instead.");
  console.log("");
  return false;
}

pictureSorter(argv['s'], argv['d'], argv);
